### ISSUE TITLE
MIDI in CC 51 not working in Wavetable mode

### ISSUE THREAD

**Issue by 01010101** [MeeBlip/meeblip-anode#2]
I have an issue with wavetable selection through MIDI IN (Meeblip Anode Firmware 2.0)
Bank selection through CC 66 works well.
But CC 51 doesn't seem to work.

Thanks for your help.

**Comment by jgrahame** [comment]
Hi,

We didn't officially add the ability to change wavetables by MIDI CC until
version 2.5.

**Comment by 01010101** [comment]
Hi,

Thx for your reply.
I figured out in between the standard Meeblip Anode firmware can be upgraded using v2.5
It's kind of unclear at first glance since it's labelled "Limited Edition" and under another repo.

May I suggest you add some info about the cross-compatibility so people don't wonder if it's a different hardware/firmware ?

PS : thanks for the great work.

**Comment by jgrahame** [comment]
Good idea. We will a note that it is the same hardware. Thanks!
